name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup_db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: wtp
          POSTGRES_USER: valid_user
          POSTGRES_PASSWORD: valid_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checka ut repo
        uses: actions/checkout@v4
      - name: Installera psql
        run: sudo apt-get install -y postgresql-client
      - name: Initiera databasstruktur
        run: |
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -f sql/init.sql
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -c "
          -- Säkerställ att roller finns
          INSERT INTO role (id, company_role) VALUES (1, 'User') ON CONFLICT (id) DO NOTHING;
          INSERT INTO role (id, company_role) VALUES (2, 'Admin') ON CONFLICT (id) DO NOTHING;
          INSERT INTO role (id, company_role) VALUES (3, 'SuperAdmin') ON CONFLICT (id) DO NOTHING;"
  api_tests_and_seed:
    needs: setup_db
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: wtp
          POSTGRES_USER: valid_user
          POSTGRES_PASSWORD: valid_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=wtp;Username=valid_user;Password=valid_password;Include Error Detail=true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Cleanup Database
        run: |
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -c "
          DELETE FROM users WHERE email = 'newstaff@example.com';"
      - name: Initiera databasstruktur
        run: |
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -f sql/init.sql
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -c "
          INSERT INTO role (id, company_role) VALUES (1, 'User') ON CONFLICT (id) DO NOTHING;
          INSERT INTO role (id, company_role) VALUES (2, 'Admin') ON CONFLICT (id) DO NOTHING;
          INSERT INTO role (id, company_role) VALUES (3, 'SuperAdmin') ON CONFLICT (id) DO NOTHING;"
      - name: Uppdatera appsettings.json
        run: |
          sed -i 's/"DefaultConnection": ".*"/"DefaultConnection": "Host=localhost;Port=5432;Database=wtp;Username=valid_user;Password=valid_password;"/' ./WTP-main/server/appsettings.json
      - name: Seed testdata
        run: |
          PGPASSWORD=valid_password psql -h localhost -U valid_user -d wtp -c "
          INSERT INTO public.users (first_name, password, created_at, company, role_id, email) 
          VALUES ('admin', 'admin321', '2025-04-07 07:42:10.181265 +00:00', 'fordon', 2, 'admin@admin.com')
          ON CONFLICT (email) DO UPDATE SET password = 'admin321';"
  postman_tests:
    needs: api_tests_and_seed
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut repo
        uses: actions/checkout@v4
      - name: Installera curl
        run: sudo apt-get install -y curl
      - name: Ensure Services Are Ready
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 10 http://localhost:5000/api/health
          curl --retry 5 --retry-connrefused --retry-delay 10 http://localhost:3001
      - name: Kör Postman-tester
        run: |
          newman run postman/WTP.postman_collection.json \
            -e postman/WTP_environment.postman_environment.json \
            --insecure \
            --reporters cli,json \
            --reporter-json-export newman-results.json
  gui_tests:
    needs: api_tests_and_seed
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=wtp;Username=valid_user;Password=valid_password;Include Error Detail=true
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Uppdatera AdminDeleteUserSteps för bättre CI-kompatibilitet
        run: |
          if [ -f "N2NTest/Steps/AdminDeleteUserSteps.cs" ]; then
            sed -i 's/Timeout = 20000/Timeout = 60000/g' N2NTest/Steps/AdminDeleteUserSteps.cs
          fi
      - name: Kör Playwright GUI-tester
        run: |
          dotnet test
